# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuhRNRDppCZkEYsWJ-xycLCEaENpRzk9
"""

from keras.datasets import mnist
from keras.utils import to_categorical
from keras import layers
from keras import models
from keras.layers import Input # Import Input layer
# Removed image processing imports (os, numpy, PIL.Image, matplotlib.pyplot) as they are moved to the prediction cell.

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Process training images
train_images_processed = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255

# Process test images
test_images_processed = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255

# Convert labels to categorical
train_labels_categorical = to_categorical(train_labels)
test_labels_categorical = to_categorical(test_labels)

# Define the Input layer
input_tensor = Input(shape=(28, 28, 1))

# Build the model using the Functional API
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(input_tensor)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dropout(0.5)(x)
output_tensor = layers.Dense(10, activation='softmax')(x)

model = models.Model(inputs=input_tensor, outputs=output_tensor)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
model.fit(train_images_processed, train_labels_categorical, epochs=10, batch_size=64)

from keras.datasets import mnist
from keras.utils import to_categorical
from keras import layers
from keras import models
from keras.layers import Input # Import Input layer
# Removed image processing imports (os, numpy, PIL.Image, matplotlib.pyplot) as they are moved to the prediction cell.

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Process training images
train_images_processed = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255

# Process test images
test_images_processed = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255

# Convert labels to categorical
train_labels_categorical = to_categorical(train_labels)
test_labels_categorical = to_categorical(test_labels)

# Define the Input layer
input_tensor = Input(shape=(28, 28, 1))

# Build the model using the Functional API
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(input_tensor)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dropout(0.5)(x)
output_tensor = layers.Dense(10, activation='softmax')(x)

model = models.Model(inputs=input_tensor, outputs=output_tensor)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
model.fit(train_images_processed, train_labels_categorical, epochs=10, batch_size=64)

import matplotlib.pyplot as plt
import numpy as np

# Display some test images with their labels
num_images = 5 # Number of images to display

plt.figure(figsize=(10, 5))
for i in range(num_images):
    # Select a random image index
    idx = np.random.randint(0, len(test_images))

    plt.subplot(1, num_images, i + 1)
    plt.imshow(test_images[idx], cmap='gray')
    plt.title(f"Label: {test_labels[idx]}")
    plt.axis('off')
plt.suptitle('Sample MNIST Test Images', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

from keras.datasets import mnist
from keras.utils import to_categorical
from keras import layers
from keras import models
from keras.layers import Input
import numpy as np

# Load and preprocess data
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images_processed = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255
test_images_processed = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255
train_labels_categorical = to_categorical(train_labels)
test_labels_categorical = to_categorical(test_labels)

# Define the Input layer
input_tensor = Input(shape=(28, 28, 1))

# Build the model using the Functional API
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(input_tensor)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(64, (3, 3), activation='relu', padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dropout(0.5)(x)
output_tensor = layers.Dense(10, activation='softmax')(x)

model = models.Model(inputs=input_tensor, outputs=output_tensor)

# Compile and train the model (ONLY 5 EPOCHS)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images_processed, train_labels_categorical, epochs=5, batch_size=64)

# Evaluate the model on the test dataset
test_loss, test_acc = model.evaluate(test_images_processed, test_labels_categorical)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")

# PREDICT AND DISPLAY THE PREDICTED NUMBERS FOR FIRST 10 TEST IMAGES
predictions = model.predict(test_images_processed[:10])

print("\n" + "="*50)
print("PREDICTION RESULTS (First 10 test images)")
print("="*50)

for i in range(10):
    predicted_digit = np.argmax(predictions[i])
    actual_digit = test_labels[i]
    confidence = np.max(predictions[i]) * 100
    print(f"Image {i+1}: Predicted = {predicted_digit} | Actual = {actual_digit} | Confidence = {confidence:.2f}%")

# Optionally, predict for a specific image you provide
print("\n" + "="*50)
print("PREDICT FOR A SPECIFIC TEST IMAGE")
print("="*50)

# Example: Predict for test image at index 42
index_to_predict = 42
single_prediction = model.predict(test_images_processed[index_to_predict:index_to_predict+1])
predicted_number = np.argmax(single_prediction)
confidence_score = np.max(single_prediction) * 100

print(f"Test Image #{index_to_predict}")
print(f"Predicted Number: {predicted_number}")
print(f"Actual Number: {test_labels[index_to_predict]}")
print(f"Confidence: {confidence_score:.2f}%")

# Function to predict any image by its index
def predict_image(index):
    """Predict the digit for a specific test image by its index"""
    pred = model.predict(test_images_processed[index:index+1])
    digit = np.argmax(pred)
    conf = np.max(pred) * 100
    print(f"Image {index}: Predicted = {digit} | Actual = {test_labels[index]} | Confidence = {conf:.2f}%")
    return digit

# Example usage of the function
print("\n" + "="*50)
print("USING THE PREDICT FUNCTION")
print("="*50)
predict_image(100)  # Predict the 100th test image

import matplotlib.pyplot as plt
import numpy as np

# Get predictions for the entire test set
all_predictions = model.predict(test_images_processed)
predicted_labels = np.argmax(all_predictions, axis=1)

# Find indices where predictions are incorrect
incorrect_indices = np.where(predicted_labels != test_labels)[0]

print(f"Total incorrect predictions: {len(incorrect_indices)}")

# Display some of the incorrectly predicted images
num_display = min(10, len(incorrect_indices)) # Display up to 10 incorrect predictions

if num_display > 0:
    plt.figure(figsize=(15, 6))
    plt.suptitle('Misclassified MNIST Test Images', fontsize=16)

    for i in range(num_display):
        idx = incorrect_indices[i]
        plt.subplot(2, 5, i + 1) # Adjust subplot grid based on num_display
        plt.imshow(test_images[idx], cmap='gray')
        plt.title(f"Pred: {predicted_labels[idx]}\nActual: {test_labels[idx]}")
        plt.axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
    plt.show()
else:
    print("No incorrect predictions to display!")